# Required Libraries

In [1]:
import numpy as np
import pandas as pd

# Numpy

> ## Numpy Array

In [2]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
myarr=np.array(l1)

> ## Change DataType

In [3]:
myarr=np.array(l1,dtype=float)
myarr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

> ## Method of Numpy

In [4]:
print("my array size is",myarr.size)
print("my array type is ",myarr.dtype)
print("my array deminision is ",myarr.ndim)
print("my array shape is ",myarr.shape)

my array size is 9
my array type is  float64
my array deminision is  2
my array shape is  (3, 3)


> ## Arange method for Sequence Series

In [5]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

> ## Random numbers

In [6]:
np.random.random(size=5) # 0-1

array([0.87051271, 0.825496  , 0.97216773, 0.41069562, 0.62660616])

In [7]:
np.random.randint(1,7,size=1)

array([5])

> ## Boolean_indexing

In [8]:
np.random.seed(123)
arr=np.random.randint(30,size=10)
arr

array([13,  2, 28,  2,  6, 17, 19, 10, 27, 25])

In [9]:
arr>10

array([ True, False,  True, False, False,  True,  True, False,  True,
        True])

In [10]:
arr[arr>10]

array([13, 28, 17, 19, 27, 25])

> ## Index Value

In [11]:
np.where(arr>10)

(array([0, 2, 5, 6, 8, 9]),)

> ## bitwise Operator

In [12]:
arr[(arr>20) & (arr<30)]

array([28, 27, 25])

In [13]:
arr[np.where((arr>20) & (arr<30))]

array([28, 27, 25])

> ## copy, delete, append, insert,sort & flip method

In [14]:
b=np.copy(arr)
b

array([13,  2, 28,  2,  6, 17, 19, 10, 27, 25])

In [15]:
np.delete(b,[1,2])

array([13,  2,  6, 17, 19, 10, 27, 25])

In [16]:
np.append(b,[10,11,12])

array([13,  2, 28,  2,  6, 17, 19, 10, 27, 25, 10, 11, 12])

In [17]:
np.insert(b,4,[33])

array([13,  2, 28,  2, 33,  6, 17, 19, 10, 27, 25])

In [18]:
np.flip(np.sort(b))

array([28, 27, 25, 19, 17, 13, 10,  6,  2,  2])

> ## identity & zero matrix

In [19]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Reshape

In [22]:
l1=[1,2,3]
l2=[4,5,6]

arr=np.array([l1,l2])

print(arr.shape)

print(arr)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [23]:
arr.reshape(3,2,order="C") # F is for column and C is rows
arr

array([[1, 2, 3],
       [4, 5, 6]])

### Transpose

In [24]:
np.transpose(arr)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# pandas Series

> ## Empty Series

In [26]:
pd.Series()

Series([], dtype: object)

> ## Series Example

In [27]:
pd.Series(['A','B','C'],index=np.arange(1,4))

1    A
2    B
3    C
dtype: object

> ## Series using Dictionary

In [28]:
dic={1:'A',2:'B',3:'C'}
ser=pd.Series(dic)

> ## Sorting Values

In [29]:
ser.sort_values(ascending=False)

3    C
2    B
1    A
dtype: object

> ## Sorting Index

In [30]:
ser.sort_index()

1    A
2    B
3    C
dtype: object

> ## Some methods of Series

In [31]:
dic={'a1':36,'a2':13,'a3':30,'a4':36,'a5':46}
ser=pd.Series(dic)

In [32]:
ser

a1    36
a2    13
a3    30
a4    36
a5    46
dtype: int64

In [33]:
ser.mean()

32.2

In [34]:
ser.sum()

161

In [35]:
ser.between(30,40)

a1     True
a2    False
a3     True
a4     True
a5    False
dtype: bool

> ## Droping

In [36]:
ser.drop('a5',inplace=True)
ser

a1    36
a2    13
a3    30
a4    36
dtype: int64

## Pandas DataFrame

> ## Empty DataFrame

In [37]:
df=pd.DataFrame()

> ## Creating your own dataframe

In [38]:
ser_dict={'Name':['Rachel','Ross','joey','chandler','monica','phoebe','tom','jerry','noddy','doremon','nobita','bheem','raju','moon','guru'],
          'Salary':[27173,22354,27930,28137,28053,21806,28366,27246,20452,24030,27008,24696,24297,23423,45452]}

In [39]:
df=pd.DataFrame(ser_dict)
df

Name  Salary
0     Rachel   27173
1       Ross   22354
2       joey   27930
3   chandler   28137
4     monica   28053
5     phoebe   21806
6        tom   28366
7      jerry   27246
8      noddy   20452
9    doremon   24030
10    nobita   27008
11     bheem   24696
12      raju   24297
13      moon   23423
14      guru   45452

> ## Reading Data File
- \*.csv -> pd.read_csv(*.csv)
- \*.xlsx -> pd.read_excel(*.xlsx, sheet=None)

In [40]:
df=pd.read_csv('data/Bank Churn.csv')

> ## Head & Tail
- Head -> first 5 rows
- Tail -> last 5 rows

In [41]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [42]:
df.tail()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0

> ## Null values in %

In [43]:
df.isnull().sum()/len(df)*100

CreditScore        0.0
Geography          0.0
Gender             0.0
Age                0.0
Tenure             0.0
Balance            0.0
NumOfProducts      0.0
HasCrCard          0.0
IsActiveMember     0.0
EstimatedSalary    0.0
Exited             0.0
dtype: float64

> ## Quick insights at your Data

- df.shape: Returns a tuple representing the dimensions of the DataFrame, with the format (rows, columns).

- df.info(): Displays a concise summary of the DataFrame, including the number of non-null entries, data types, and memory usage.

- df.describe(): Generates descriptive statistics of the DataFrame's numerical columns

In [44]:
df.shape

(10000, 11)

The most common data types in pandas:
- int64 (integer)
- float64 (floating point number)
- object (string)
- datetime (datetime)
- bool (true or false)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [46]:
# Convert the SalePrice column into float64 data type

df['Balance'].astype('int64')

0            0
1        83807
2       159660
3            0
4       125510
         ...  
9995         0
9996     57369
9997         0
9998     75075
9999    130142
Name: Balance, Length: 10000, dtype: int64

In [47]:
df.describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary        Exited  
count  10000.00000    10000.000000     10000.000000  10000.000000  
mean       0.70550        0.515100    100090.239881      0.203700  
std        0.45584        0.499797     57510.492818      0.402769  
min        0.00000        0.000000        11.580000      0.000000  
25%        0.00000        0.000000     51002.110000      0.000000  
50%        1.00000        1.000000    100193.915000      0.000000  
75%        1.00000        1.000000    149388.247500      0.000000  
max        1.00000        1.000000    199992.480000      1.000000

> ## Selecting a column in a dataframe

In [48]:
df[['CreditScore']]

CreditScore
0             619
1             608
2             502
3             699
4             850
...           ...
9995          771
9996          516
9997          709
9998          772
9999          792

[10000 rows x 1 columns]

In [49]:
df[['CreditScore', 'Geography', 'Gender']]

CreditScore Geography  Gender
0             619    France  Female
1             608     Spain  Female
2             502    France  Female
3             699    France  Female
4             850     Spain  Female
...           ...       ...     ...
9995          771    France    Male
9996          516    France    Male
9997          709    France  Female
9998          772   Germany    Male
9999          792    France  Female

[10000 rows x 3 columns]

In [50]:
df.CreditScore

0       619
1       608
2       502
3       699
4       850
       ... 
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [51]:
# Rename 'Valves_Per_Cylinder'

df.rename(columns={'Valves_Per_Cylinder':'values_per_cylinder'})

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

> ## Index-based selection
We use iloc to select data based on their numerical position in the dataframe.

In [52]:
df.iloc[4:10,[0,1,2,3,6,7]]

CreditScore Geography  Gender  Age  NumOfProducts  HasCrCard
4          850     Spain  Female   43              1          1
5          645   espanio    Male   44              2          1
6          822       fra    Male   50              2          1
7          376   Germany  Female   29              4          1
8          501    France    Male   44              2          0
9          684    France    Male   27              1          1

> ## Label-based selection
With loc we need to specify the actual name of the column.

In [53]:
df.loc[:,['CreditScore', 'Geography', 'Gender', 'Age','Tenure', 'Balance', 'NumOfProducts']]

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts
0             619    France  Female   42       2       0.00              1
1             608     Spain  Female   41       1   83807.86              1
2             502    France  Female   42       8  159660.80              3
3             699    France  Female   39       1       0.00              2
4             850     Spain  Female   43       2  125510.82              1
...           ...       ...     ...  ...     ...        ...            ...
9995          771    France    Male   39       5       0.00              2
9996          516    France    Male   35      10   57369.61              1
9997          709    France  Female   36       7       0.00              1
9998          772   Germany    Male   42       3   75075.31              2
9999          792    France  Female   28       4  130142.79              1

[10000 rows x 7 columns]

> ## Conditional Selection

In [54]:
df.loc[df['Gender']=='Male',:]

CreditScore Geography Gender  Age  Tenure    Balance  NumOfProducts  \
5             645   espanio   Male   44       8  113755.78              2   
6             822       fra   Male   50       7       0.00              2   
8             501    France   Male   44       4  142051.07              2   
9             684    France   Male   27       2  134603.88              1   
10            528    France   Male   31       6  102016.72              2   
...           ...       ...    ...  ...     ...        ...            ...   
9992          726     Spain   Male   36       2       0.00              1   
9993          644    France   Male   28       7  155060.41              1   
9995          771    France   Male   39       5       0.00              2   
9996          516    France   Male   35      10   57369.61              1   
9998          772   Germany   Male   42       3   75075.31              2   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
5             1               0        149756.71       1  
6             1               1         10062.80       0  
8             0               1         74940.50       0  
9             1               1         71725.73       0  
10            0               0         80181.12       0  
...         ...             ...              ...     ...  
9992          1               0        195192.40       0  
9993          1               0         29179.52       0  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9998          1               0         92888.52       1  

[5457 rows x 11 columns]

In [55]:
df.loc[(df['CreditScore'] > 700) & (df['Gender'] == 'Female') ,:]

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
4             850     Spain  Female   43       2  125510.82              1   
19            726    France  Female   24       6       0.00              2   
24            846    France  Female   38       5       0.00              1   
34            722     Spain  Female   29       9       0.00              2   
43            834    France  Female   49       2  131394.56              1   
...           ...       ...     ...  ...     ...        ...            ...   
9960          795   Germany  Female   33       9  104552.72              1   
9971          833    France  Female   34       3  144751.81              1   
9994          800    France  Female   29       2       0.00              2   
9997          709    France  Female   36       7       0.00              1   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
4             1               1         79084.10       0  
19            1               1         54724.03       0  
24            1               1        187616.16       0  
34            1               1        142033.07       0  
43            0               0        194365.76       1  
...         ...             ...              ...     ...  
9960          1               1        120853.83       1  
9971          0               0        166472.81       0  
9994          0               0        167773.55       0  
9997          0               1         42085.58       1  
9999          1               0         38190.78       0  

[1415 rows x 11 columns]

In [56]:
df.loc[(df['CreditScore'] > 800) | (df['Age'] == 50) ,:]

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
4             850     Spain  Female   43       2  125510.82              1   
6             822       fra    Male   50       7       0.00              2   
24            846    France  Female   38       5       0.00              1   
37            804     Spain    Male   33       7   76548.60              1   
38            850    France    Male   36       7       0.00              1   
...           ...       ...     ...  ...     ...        ...            ...   
9931          850    France  Female   34       6  101266.51              1   
9949          850    France  Female   47       9  137301.87              1   
9971          833    France  Female   34       3  144751.81              1   
9975          610   Germany    Male   50       1  113957.01              2   
9989          841     Spain    Male   28       4       0.00              2   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
4             1               1         79084.10       0  
6             1               1         10062.80       0  
24            1               1        187616.16       0  
37            0               1         98453.45       0  
38            1               1         40812.90       0  
...         ...             ...              ...     ...  
9931          1               0         33501.98       0  
9949          1               0         44351.77       0  
9971          0               0        166472.81       0  
9975          1               0        196526.55       1  
9989          1               1        179436.60       0  

[772 rows x 11 columns]

In [57]:
# assigning values in column using loc

df.loc[df['Geography']=='fra','Geography']='France'
df.loc[df['Geography']=='france','Geography']='France'
df.loc[df['Geography']=='espanio','Geography']='Spain'
df.loc[df['Geography']=='spain','Geography']='Spain'
df.loc[df['Geography']=='ger','Geography']='Germany'
df.loc[df['Geography']=='germany','Geography']='Germany'
df.loc[df['Geography']=='gernamy','Geography']='Germany'
df.loc[df['Geography']=='GERMANY','Geography']='Germany'

> ## Unique and value counts function

In [58]:
# How many unique Geography values are there?

df['Geography'].nunique()

3

In [59]:
# What are the unique Geography values?

df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [60]:
# What are the counts of those individual values?

df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

> ## Descriptive statistics

In [61]:
df['Age'].max()

92

In [62]:
df['Age'].min()

18

In [63]:
df['Age'].mean()

38.9218

In [64]:
df['Age'].median()

37.0

In [65]:
df['Geography'].mode()

0    France
Name: Geography, dtype: object

> ## Map and apply function

In [66]:
def convert_to_lakhs(n):
  return f'{n/100000:.2f} Lakhs'

df['Balance(Lakhs)']=df['Balance'].apply(convert_to_lakhs)
df['Balance(Lakhs)'].head()

0    0.00 Lakhs
1    0.84 Lakhs
2    1.60 Lakhs
3    0.00 Lakhs
4    1.26 Lakhs
Name: Balance(Lakhs), dtype: object

In [67]:
df['Encoded Gender'] = df['Gender'].map({'Male':1, 'Female':0})

df[['Gender', 'Encoded Gender']].tail()

Gender  Encoded Gender
9995    Male               1
9996    Male               1
9997  Female               0
9998    Male               1
9999  Female               0

> ## GroupBy

In [68]:
df=pd.read_csv('data/gun_violence_data.csv')
df.head()

incident_id        date           state city_or_county  \
0       461105  2013-01-01    Pennsylvania     Mckeesport   
1       460726  2013-01-01      California      Hawthorne   
2       478855  2013-01-01            Ohio         Lorain   
3       478925  2013-01-05        Colorado         Aurora   
4       478959  2013-01-07  North Carolina     Greensboro   

                                     address  n_killed  n_injured  \
0  1506 Versailles Avenue and Coursin Street         0          4   
1               13500 block of Cerise Avenue         1          3   
2                      1776 East 28th Street         1          3   
3           16000 block of East Ithaca Place         4          0   
4                  307 Mourning Dove Terrace         2          2   

                                        incident_url  \
0  http://www.gunviolencearchive.org/incident/461105   
1  http://www.gunviolencearchive.org/incident/460726   
2  http://www.gunviolencearchive.org/incident/478855   
3  http://www.gunviolencearchive.org/incident/478925   
4  http://www.gunviolencearchive.org/incident/478959   

                                          source_url  \
0  http://www.post-gazette.com/local/south/2013/0...   
1  http://www.dailybulletin.com/article/zz/201301...   
2  http://chronicle.northcoastnow.com/2013/02/14/...   
3  http://www.dailydemocrat.com/20130106/aurora-s...   
4  http://www.journalnow.com/news/local/article_d...   

   incident_url_fields_missing  ...                    participant_age  \
0                        False  ...                              0::20   
1                        False  ...                              0::20   
2                        False  ...  0::25||1::31||2::33||3::34||4::33   
3                        False  ...         0::29||1::33||2::56||3::33   
4                        False  ...         0::18||1::46||2::14||3::47   

                               participant_age_group  \
0  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
1  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
2  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
3  0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...   
4  0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...   

                            participant_gender  \
0         0::Male||1::Male||3::Male||4::Female   
1                                      0::Male   
2  0::Male||1::Male||2::Male||3::Male||4::Male   
3         0::Female||1::Male||2::Male||3::Male   
4       0::Female||1::Male||2::Male||3::Female   

                                    participant_name  \
0                                     0::Julian Sims   
1                                  0::Bernard Gillis   
2  0::Damien Bell||1::Desmen Noble||2::Herman Sea...   
3  0::Stacie Philbrook||1::Christopher Ratliffe||...   
4  0::Danielle Imani Jameison||1::Maurice Eugene ...   

   participant_relationship  \
0                       NaN   
1                       NaN   
2                       NaN   
3                       NaN   
4                 3::Family   

                                  participant_status  \
0  0::Arrested||1::Injured||2::Injured||3::Injure...   
1      0::Killed||1::Injured||2::Injured||3::Injured   
2  0::Injured, Unharmed, Arrested||1::Unharmed, A...   
3         0::Killed||1::Killed||2::Killed||3::Killed   
4       0::Injured||1::Injured||2::Killed||3::Killed   

                                    participant_type  \
0  0::Victim||1::Victim||2::Victim||3::Victim||4:...   
1  0::Victim||1::Victim||2::Victim||3::Victim||4:...   
2  0::Subject-Suspect||1::Subject-Suspect||2::Vic...   
3  0::Victim||1::Victim||2::Victim||3::Subject-Su...   
4  0::Victim||1::Victim||2::Victim||3::Subject-Su...   

                                             sources state_house_district  \
0  http://pittsburgh.cbslocal.com/2013/01/01/4-pe...                  NaN   
1  http://losangeles.cbslocal.com/2013/01/01/man-...                 62.0   
2  http://www.morningjournal.com/ge

In [69]:
df=df[[ 'date', 'state', 'n_killed','n_injured']]


In [70]:
# Import library for datetime
from datetime import datetime 

df['date'] = pd.to_datetime(df['date']) # convert date to datetime format
df['year'] = df['date'].dt.year # extract year
df['month'] = df['date'].dt.month # extract month
df['day'] = df['date'].dt.day # extract day
df['day_of_week'] = df['date'].dt.dayofweek # extract day of week
df['total_victim'] = df['n_killed'] + df['n_injured'] # sum up number of deaths and injuries
df.head()

date           state  n_killed  n_injured  year  month  day  \
0 2013-01-01    Pennsylvania         0          4  2013      1    1   
1 2013-01-01      California         1          3  2013      1    1   
2 2013-01-01            Ohio         1          3  2013      1    1   
3 2013-01-05        Colorado         4          0  2013      1    5   
4 2013-01-07  North Carolina         2          2  2013      1    7   

   day_of_week  total_victim  
0            1             4  
1            1             4  
2            1             4  
3            5             4  
4            0             4

In [71]:
df['day_of_week'] = df['day_of_week'].map({0: 'Monday', 1: 'Tuesday', 2: 'Wednesday', 3: 'Thursday', 4: 'Friday', 5: 'Saturday', 6: 'Sunday'})
df.head()

date           state  n_killed  n_injured  year  month  day  \
0 2013-01-01    Pennsylvania         0          4  2013      1    1   
1 2013-01-01      California         1          3  2013      1    1   
2 2013-01-01            Ohio         1          3  2013      1    1   
3 2013-01-05        Colorado         4          0  2013      1    5   
4 2013-01-07  North Carolina         2          2  2013      1    7   

  day_of_week  total_victim  
0     Tuesday             4  
1     Tuesday             4  
2     Tuesday             4  
3    Saturday             4  
4      Monday             4

In [72]:
df['day_of_week'].value_counts()

day_of_week
Wednesday    1574
Sunday       1473
Saturday     1469
Thursday     1454
Monday       1412
Friday       1337
Tuesday      1281
Name: count, dtype: int64

In [73]:
df.groupby('day_of_week')['total_victim'].count()

day_of_week
Friday       1337
Monday       1412
Saturday     1469
Sunday       1473
Thursday     1454
Tuesday      1281
Wednesday    1574
Name: total_victim, dtype: int64

In [74]:
df.groupby('state')['total_victim'].sum()

state
Alabama                 209
Alaska                   20
Arizona                 109
Arkansas                 90
California              764
Colorado                 88
Connecticut              52
Delaware                 40
District of Columbia     85
Florida                 641
Georgia                 232
Hawaii                    6
Idaho                     9
Illinois                409
Indiana                 243
Iowa                     60
Kansas                   71
Kentucky                106
Louisiana               352
Maine                    12
Maryland                175
Massachusetts            59
Michigan                221
Minnesota                51
Mississippi             145
Missouri                193
Montana                  22
Nebraska                 22
Nevada                   58
New Hampshire            11
New Jersey              199
New Mexico               47
New York                290
North Carolina          309
North Dakota              4
Ohio          

In [75]:
df.groupby('month')['total_victim'].agg([np.mean, min, max])

/var/folders/_n/lm2hjpwd7w3777gk6rhsk8zc0000gn/T/ipykernel_50524/1903916318.py:1: FutureWarning: The provided callable <function mean at 0x106605760> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('month')['total_victim'].agg([np.mean, min, max])
/var/folders/_n/lm2hjpwd7w3777gk6rhsk8zc0000gn/T/ipykernel_50524/1903916318.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('month')['total_victim'].agg([np.mean, min, max])
/var/folders/_n/lm2hjpwd7w3777gk6rhsk8zc0000gn/T/ipykernel_50524/1903916318.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will 

mean  min  max
month                    
1      0.682993    0    7
2      0.695780    0   12
3      0.733159    0   13
4      4.588235    4    7
5      4.481481    1   19
6      5.032258    4    9
7      4.176471    1    7
8      4.250000    1    8
9      5.250000    4   14
10     4.863636    1   13
11     4.956522    1   18
12     3.909091    1    8

In [76]:
# Total number of victims in each state from highest to lowest 

df.groupby('month')['total_victim'].sum().sort_values(ascending=False)

month
1     3012
2     2127
3     1687
6      156
9      147
7      142
5      121
8      119
11     114
10     107
12      86
4       78
Name: total_victim, dtype: int64

> ## Dealing with missing values

In [77]:
df=pd.read_csv('data/House_Price.csv')
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

> #### Method 1: Drop rows or columns with missing values
Remove rows or columns that contain missing values. However, this is not the best approach in most cases because we might lose potentially useful information in our dataset.

In [78]:
# Drop rows with missing values

df.dropna(axis=0, inplace=False)

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

OOP!! , it appears that we have dropped all the rows in our dataframe

In [79]:
# Drop columns with missing values

df.dropna(axis=1, inplace=False)

Id  MSSubClass MSZoning  LotArea Street LotShape LandContour  \
0        1          60       RL     8450   Pave      Reg         Lvl   
1        2          20       RL     9600   Pave      Reg         Lvl   
2        3          60       RL    11250   Pave      IR1         Lvl   
3        4          70       RL     9550   Pave      IR1         Lvl   
4        5          60       RL    14260   Pave      IR1         Lvl   
...    ...         ...      ...      ...    ...      ...         ...   
1455  1456          60       RL     7917   Pave      Reg         Lvl   
1456  1457          20       RL    13175   Pave      Reg         Lvl   
1457  1458          70       RL     9042   Pave      Reg         Lvl   
1458  1459          20       RL     9717   Pave      Reg         Lvl   
1459  1460          20       RL     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0       AllPub    Inside       Gtl  ...             0         0           0   
1       AllPub       FR2       Gtl  ...             0         0           0   
2       AllPub    Inside       Gtl  ...             0         0           0   
3       AllPub    Corner       Gtl  ...           272         0           0   
4       AllPub       FR2       Gtl  ...             0         0           0   
...        ...       ...       ...  ...           ...       ...         ...   
1455    AllPub    Inside       Gtl  ...             0         0           0   
1456    AllPub    Inside       Gtl  ...             0         0           0   
1457    AllPub    Inside       Gtl  ...             0         0           0   
1458    AllPub    Inside       Gtl  ...           112         0           0   
1459    AllPub    Inside       Gtl  ...             0         0           0   

     PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0           0       0       2    2008        WD         Normal    208500  
1           0       0       5    2007        WD         Normal    181500  
2           0       0       9    2008        WD         Normal    223500  
3           0       0       2    2006        WD        Abnorml    140000  
4           0       0      12    2008        WD         Normal    250000  
...       ...     ...     ...     ...       ...            ...       ...  
1455        0       0       8    2007        WD         Normal    175000  
1456        0       0       2    2010        WD         Normal    210000  
1457        0    2500       5    2010        WD         Normal    266500  
1458        0       0       4    2010        WD         Normal    142125  
1459        0       0       6    2008        WD         Normal    147500  

[1460 rows x 62 columns]

we have drop 19 columns which where having null values

> #### Method 2: Filling in missing values
- Using mean or median values (for numerical variables)
- Using mode or zero (for categorical variables)

In [80]:
df['LotFrontage'].dtype

dtype('float64')

In [81]:
df['LotFrontage'].median()

69.0

In [82]:
# Impute missing data in LotFrontage with median

df['LotFrontage'] =df['LotFrontage'].fillna(df['LotFrontage'].median())
df['LotFrontage'].head(10)

0    65.0
1    80.0
2    68.0
3    60.0
4    84.0
5    85.0
6    75.0
7    69.0
8    51.0
9    50.0
Name: LotFrontage, dtype: float64

In [83]:
df['GarageType'].dtype


dtype('O')

In [84]:
df['GarageType'].mode()[0]

'Attchd'

In [85]:

df['GarageType'] = df['GarageType'].fillna(df['GarageType'].mode()[0])
df['GarageType'].head()

0    Attchd
1    Attchd
2    Attchd
3    Detchd
4    Attchd
Name: GarageType, dtype: object

In [86]:
df['GarageQual'].value_counts(dropna=False)

GarageQual
TA     1311
NaN      81
Fa       48
Gd       14
Ex        3
Po        3
Name: count, dtype: int64

In [87]:
df['GarageQual'] = df['GarageQual'].fillna('Unknown')
df['GarageQual'].value_counts()

GarageQual
TA         1311
Unknown      81
Fa           48
Gd           14
Ex            3
Po            3
Name: count, dtype: int64

> ## Combining dataframe

In [88]:
df1 = pd.DataFrame({'Name': ['Vicky', 'Bill'], 'Age': [12, 46]})
df2 = pd.DataFrame({'Name': ['John', 'Sabrina'], 'Age': [37, 25]})

print('First DataFrame:\n')
print(df1)
print('\n')
print('Second DataFrame:\n')
print(df2)

First DataFrame:

    Name  Age
0  Vicky   12
1   Bill   46


Second DataFrame:

      Name  Age
0     John   37
1  Sabrina   25


> #### Concat

In [89]:
# Concat horizontally

pd.concat([df1, df2], axis = 1)

Name  Age     Name  Age
0  Vicky   12     John   37
1   Bill   46  Sabrina   25

In [90]:
# Concat vertically and ignore index

df3 = pd.concat([df1, df2], axis = 0)
df3

Name  Age
0    Vicky   12
1     Bill   46
0     John   37
1  Sabrina   25

In [91]:
df4 = pd.DataFrame({'Name': ['Tyler', 'Natalie'], 'Age': [28, 39], 'Hobby': ['Swimming', 'Reading']})
df4

Name  Age     Hobby
0    Tyler   28  Swimming
1  Natalie   39   Reading

In [92]:
# Outer is the default for the join argument

pd.concat([df3, df4], join = 'outer', ignore_index = True)

Name  Age     Hobby
0    Vicky   12       NaN
1     Bill   46       NaN
2     John   37       NaN
3  Sabrina   25       NaN
4    Tyler   28  Swimming
5  Natalie   39   Reading

Outer does not consider any differences in columns between two dataframe. Because df3 does not have a hobby column, pandas will automatically fill them with null values.

In [93]:
# Inner stacks only the columns that are shared between the two dataframes

pd.concat([df3, df4], join = 'inner', ignore_index = True)

Name  Age
0    Vicky   12
1     Bill   46
2     John   37
3  Sabrina   25
4    Tyler   28
5  Natalie   39

> #### Merge

In [94]:
size = pd.DataFrame({'Colour': ['Red', 'Blue', 'Green'], 'Size': ['M', 'S', 'M']})
gender = pd.DataFrame({'Colour': ['Red', 'Blue', 'Yellow'], 'Sex': ['Female', 'Female', 'Male']})
size               

Colour Size
0    Red    M
1   Blue    S
2  Green    M

In [95]:
gender

Colour     Sex
0     Red  Female
1    Blue  Female
2  Yellow    Male

In [96]:
# Only show rows where there is a match in the column
# Red and blue are present in both dataframes

pd.merge(size, gender, how = 'inner')

Colour Size     Sex
0    Red    M  Female
1   Blue    S  Female

In [97]:
# Show all the rows and fill rows with null values when there is no match
# There is no sex info on green colour and there is no size info on yellow colour

pd.merge(size, gender, how = 'outer')

Colour Size     Sex
0    Blue    S  Female
1   Green    M     NaN
2     Red    M  Female
3  Yellow  NaN    Male

In [98]:
# Keep everything that is on the left dataframe which is df1 in this example
# Fill in sex info for rows that have matches with df2 and if there is none e.g. green colour, fill null value

pd.merge(size, gender, how = 'left')

Colour Size     Sex
0    Red    M  Female
1   Blue    S  Female
2  Green    M     NaN

In [99]:
# Keep everything that is on the right dataframe which is df2 in this example
# Fill in size info for rows that have matches with df1 and if there is none e.g. yellow colour, fill null value

pd.merge(size, gender, how = 'right')

Colour Size     Sex
0     Red    M  Female
1    Blue    S  Female
2  Yellow  NaN    Male